// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUMDeW56bP1Z8U-SPZ7bufVYup5I9gN1Q',
    appId: '1:341577459721:web:05c8bcf5a771d56f8630d8',
    messagingSenderId: '341577459721',
    projectId: 'activityapp-b396d',
    authDomain: 'activityapp-b396d.firebaseapp.com',
    storageBucket: 'activityapp-b396d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDjJjP4j2GK5woeBKQa1eUiKs-Q9IyEhw',
    appId: '1:341577459721:android:ab84b98a2973adda8630d8',
    messagingSenderId: '341577459721',
    projectId: 'activityapp-b396d',
    storageBucket: 'activityapp-b396d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg26vYWkIMciiYtjC8lhBifASER_7Nips',
    appId: '1:341577459721:ios:a111422b200cc76a8630d8',
    messagingSenderId: '341577459721',
    projectId: 'activityapp-b396d',
    storageBucket: 'activityapp-b396d.appspot.com',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg26vYWkIMciiYtjC8lhBifASER_7Nips',
    appId: '1:341577459721:ios:d11b2c382d8a9d3e8630d8',
    messagingSenderId: '341577459721',
    projectId: 'activityapp-b396d',
    storageBucket: 'activityapp-b396d.appspot.com',
    iosBundleId: 'com.example.tp2.RunnerTests',
  );
}
